name: Release CLI Macos 11
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
          - os: windows-2022
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            code-target: linux-arm64
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            code-target: linux-x64-musl
          - os: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            code-target: linux-arm64-musl
          - os: macos-13
            target: x86_64-apple-darwin
            code-target: darwin-x64
          - os: macos-13
            target: aarch64-apple-darwin
            code-target: darwin-arm64

    # go through all combinations in the matrix to check if the runner and target work
    name: Package ${{ matrix.code-target }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

    #   - name: Setup .NET
    #     uses: actions/setup-dotnet@v1

    #   - name: Setup Node.js
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: '18'

      # run a quick script to verify the runner and target work
      - name: Verify runner and target
        run: |
            echo "Runner: ${{ runner.os }}"
            echo "Target: ${{ matrix.target }}"
            echo "Code Target: ${{ matrix.code-target }}"
            echo "OS: ${{ runner.os }}"
            echo "OS Version: ${{ runner.os_version }}"
            echo "OS Architecture: ${{ runner.os_arch }}"
            echo "OS Image: ${{ runner.os_image }}"
            echo "OS Release: ${{ runner.os_release }}"
            echo "OS Type: ${{ runner.os_type }}"